### ISSUE TITLE
Formato fecha de captura en S2

### ISSUE THREAD

**Issue by w3ro** [PDNMX/api_docs#7]
Con el fin de homologar el formato de las fechas de captura de los 3 sistemas se sugiere corregir el formato del sistema 2:
s1= "actualizacion": "2017-07-21T17:32:28Z",
s2= "fecha_captura": "20180820T00:00:00Z", **(sugerencia: 2018-08-20T00:00:00Z)**
s3s= "fecha_captura": "2017-07-21T17:32:28Z",
s3p= "fecha_captura": "2017-07-21T17:32:28Z",

**Comment by ch3k0** [comment]
Gracias por el comentario, ya se hizo la corrección pertinente. El formato es `date-time` dentro de la especificación por lo que el error era en el ejemplo.
