### ISSUE TITLE
Falta atributo

### ISSUE THREAD

**Issue by w3ro** [PDNMX/api_docs#8]
En api_docs/S1/oas/OAS_API_Declaraciones en el campo **nivel**, en la propiedad **"enum" : [ "PRI", "SEC", "CTC", "LIC", "ESP", "MAE", "DOC" ]**, hace falta **BACHILLERATO**.

**Comment by RazielSystems** [comment]
Se agregó el valor faltante al enum
Muchas gracias.
Enum : [ PRI, SEC, BCH, CTC, LIC, ESP, MAE, DOC ]
--
