### ISSUE TITLE
Atributo type en query

### ISSUE THREAD

**Issue by pcortesp** [PDNMX/api_docs#9]
En las definiciones de los objetos "_query_", "query -> _totalIngresosMensualesNetos_", "query -> bienesInmuebles -> _superficieConstruccion_, _superficieTerreno_, _valorAdquisicion_" falta el atributo:

**"type" : "object"**

**Comment by RazielSystems** [comment]
Hola @pcortesp muchas gracias por la observación, ya realizamos la corrección necesaria
